services:
  lambda:
    image: standup-lambda:latest
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    entrypoint: "/usr/local/bin/aws-lambda-rie"
    command: ["python", "-m", "awslambdaric", "main.handler"]
